### ISSUE TITLE
Scena

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG67-build-a-tower#2]
Napraviti kompleksniju scenu/pozadinu. U pozadini bi se mogli dodati na primer random generisani tornjevi nalik na onaj koji igrac pravi. (pritom se i oni mogu graditi tokom igranja igre kako se igrac ne bi osecao usamljeno jer samo on gradi toranj)

**Comment by SimicKatarina** [comment]
Dodati su tornjevi u pozadini koji se sami grade dok igrac gradi svoj toranj
